### ISSUE TITLE
Missing carat in people template

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.github.io#1076]
https://github.com/scholarslab/scholarslab.github.io/blob/12c91a5684da77f04fc5e1b74503f60586574fe3/_layouts/people.html#L57

It's under the libcal section

**Comment by walshbr** [comment]
I'll try and get to this when I can but I don't have the site running locally in the new branch setup yet

**Comment by amandavisconti** [comment]
I'll grab this now, since I do have site running well locally

**Comment by amandavisconti** [comment]
Done in current PR
