### ISSUE TITLE
why is logo appearing in post h1s? e.g. was in https://scholarslab.lib.virginia.edu/blog/isabel-bielat-CBW/ before I made "introduction" an H2 instead of H1

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.github.io#1080]
Too many old posts use H1s to just shift all the headings, but I can't figure out why the CSS is doing this. I did change that post's H1s to H2s, so it is no longer an example of this, but it looked like this before I changed the headings:

![Image](https://github.com/user-attachments/assets/caa798d4-8e05-470b-a321-7d64a37c51d2)

**Comment by jeremyboggs** [comment]
Fixed in #7deb0af77ed1bc4ac4625884bfa56fcdb1e81676.
