### ISSUE TITLE
github-pages gem can't satisfy your Gemfile's dependencies

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.github.io#1092]
Not sure if this is new or not:
<img width="1014" alt="Screenshot 2024-08-26 at 11 15 45 AM" src="https://github.com/user-attachments/assets/b365b3d3-dfdf-4426-af73-09a78879dfc2">

**Comment by jeremyboggs** [comment]
@amandavisconti Where do you encounter this warning?

**Comment by amandavisconti** [comment]
> @amandavisconti Where do you encounter this warning?

https://github.com/scholarslab/scholarslab.github.io/actions/runs/10594572412, for example
