### ISSUE TITLE
Amanda Middle Name

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.github.io#1117]
@amandavisconti since you started using your middle name in blog posts there's a disconnect between the display name and the url - https://scholarslab.lib.virginia.edu/people/amanda-visconti/. your most recent blog post used your middle name in the author field, which doesn't display correctly since it's expecting just first-last. You'll need to either edit that one file and keep using the first-last formulation or update the people page to include middle name and then update the past references as well.

**Comment by amandavisconti** [comment]
done, thanks for reminder

**Comment by walshbr** [comment]
no prob! would have done it myself if it was just the small fix but wasn't sure how far reaching you wanted the edits to be.
