### ISSUE TITLE
Mention events higher on homepage

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.github.io#460]
I tried linking the first two instances of the word "community" to the events page, but this doesn't work with the hero text styling and isn't clear. Would prefer to include the word events somehow, or otherwise have a link to events closer to top of homepage

**Comment by jeremyboggs** [comment]
@amandavisconti Let's meet to sketch out some options?

**Comment by amandavisconti** [comment]
@jeremyboggs I'll add this to agenda for next time we meet with Laura, so we have her thoughts too
