### ISSUE TITLE
Reduce our JavaScript footprint

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.github.io#608]
### Context
Use less JavaScript.

### Process
1. Collect underpants;
2. Delete JavaScript we don't really need; Streamline the JavaScript we do need; Load the JavaScript we need only on the pages that actually need it;
3. Profit.

### Expected Result
Less JavaScript

**Comment by jeremyboggs** [comment]
Unless I'm missing something, we are referencing two different versions of jQuery:

- 3.4.0 in the `package.json` file for Node;
- 1.12.4 at the bottom of the `_layouts/default.html` file.

It seems like the _only_ place we've specifically written JavaScript using jQuery syntax is `assets/js/projectfilter.js` file.

**Comment by amandavisconti** [comment]
Probably done by August 2024 renewal (e.g. we discussed libcal meant we had to keep jquery); closing, will let @jeremyboggs reopen if desires further work
