### ISSUE TITLE
EVENTS! adding ease, Pt 1 of 2

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.github.io#973]
See final post on this ticket for list of to-dos

**Comment by amandavisconti** [comment]
A closed ticket had some ideas that could or could not be useful:
 Add & test event.html check to include end_date and/or end_time display only if present
remove "author" as event post option & template call
add speaker as event post option & template call (and style) , but make it only display if exists (some events have no speaker, e.g. transcribe-a-thon)
move "layout" column to just something the script appends to each post
make script create "slug" from hyphenating title (and remove from spreadsheet column)
Input body content too? Way to do this easily, or (far worse) set as YAML variable then {{events.content}} pulls in?
In script (not spreadsheet), add quotation marks around each input

Resources:

    about the script: http://www.evanlovely.com/utilities/jekyll/spreadsheet-to-markdown/
    the script: https://raw.githubusercontent.com/EvanLovely/csv_to_jekyll/master/csv_to_jekyll.py
    event template: https://docs.google.com/document/d/1qLncvRa6aqQPpf2BtZwGJFf_vqrLTG6EB6qoyenZxLc/edit
    sheet to turn into file: https://docs.google.com/spreadsheets/d/1AkkCmNsWGTTbLUyLvekg_nFtsDanMfqqU02QZyN-l1A/edit#gid=0

For later:

Jeremy suggests just serve directly from spreadsheet

    How to not read in & create new posts for whole spreadsheet each time (only new or changed data?)

**Comment by amandavisconti** [comment]
I'm testing out whether we could use a 2-tab Gsheet to input event info (with dropdowns/date-time formatting) and spit out the YAML to copy from the other tab (and paste into event file).

Might be moot if we find a way to import from LibCal?

**Comment by amandavisconti** [comment]
We'd like to be able to only enter events on the Library calendar, if that'll let us pull in the metadata fields we need to display on our site? Complication is can't make individual event-post pages this way.

**Comment by amandavisconti** [comment]
Update from 9/17/2024 Laura, Jeremy, Amanda meeting: 
- Jeremy will look at LibCal's API, toward adding events in LibCal and having them show up on Slab site (maybe via CSV midpoint)
- Figure out if keep current categories as-is vs. change
- Can we get DH Portal to use Library cal so we get our events auto showing there?
- Events Archive page: manual summer update, so disjoint from API and never lose events when categories get changed, events deleted from LibCal, etc.

**Comment by amandavisconti** [comment]
Update from 10/8/2024 chats:
- Jeremy is making sure we can pull past events (so they still show up on our site day after an event)
- We use LibCal to manage adding events for the given academic year; title, date, link to LibCal details page appear listed on our /events page
- Archiving events is handled separately (Amanda can do at end of each term); export CSV, plop into folder, make /events-archive display all past event details. That way we are responsible for the record (e.g. we don't lose it if someone decides to "clean up" past events in LibCal)

**Comment by amandavisconti** [comment]
We're getting close to implementation, so I'm regathering everything into this post for ease of reading:

# Jeremy 1 of 2: December
- [ ] After final event (occurs aftenoon of Wed 12/11) and before winter break(?), @jeremyboggs implements SLab site /events embed from LibCal of upcoming events; ping Amanda so can email folks
- [ ] Hold until 1/16/2025: don't remove `/_events/dh-fellows-information-session-2025-01-15.md` until 1/16 or after (Brandon may have hardlinked people there)

# Jeremy 2 of 2: Spring/only after completing above
- [ ] Check if new setup closes #1136 (close that ticket, if so)
- [ ] @jeremyboggs?: See if there's a way on /events to show today's+upcoming events at top of page, followed by a section of "recent events" containing past events from this term only (might need two API pulls?)
- [ ] @jeremyboggs?: Style /events-archive so that description text from Fall 2024 events onward is included, but doesn't clog page (e.g. is there an accessible way to hide it behind uncollapse arrows, so it's on the page and doesn't need new markdown file per past event, but only visible if you click to see it?)

# Amanda 1 of 2: December
- [x] @amandavisconti let frequent events posters (Laura, Drew, Brandon, Ammon) know change is coming
- [x] @amandavisconti copied all (including not-yet-happened) Fall 2024 events into /_past-events/2024-events
- [x] @amandavisconti removed 2 of 3 2025 events currently in /_events (Feb 2nd Tues Forum, Berger talk) to LibCal events, and deleted from SLab site
- [x] @amandavisconti emailed Laura 12/9 to make sure plan for what info gets archived per event is okay
- [ ] @amandavisconti: update /events-archive so iterates over new /2024-events folder too
- [ ] @amandavisconti Once Jeremy pings that work is done, email all staff (especially pinging frequent users Laura, Drew, Ammon, Chris, Brandon, Amanda) about new process (LibCal only, always must use "Scholars' Lab" tag) once complete
- [ ] Hold until 1/16/2025: don't remove `/_events/dh-fellows-information-session-2025-01-15.md` until 1/16 or after (Brandon may have hardlinked people there)

# Amanda 2 of 2: Spring/only after completing above
- [ ] @amandavisconti has scheduled themselves to do a manual copy of LibCal events to /_past-events at the end of spring, summer, and fall terms each year. Only copy: Event title, Speaker/instructor, Event date, Event description/body text. (I.e. no times of day, location, reg info, images)
-[ ] @amandavisconti look into automating past-term => SLab events archive more (eg CSV export=> display from CSV in folder's data?)
- [ ] @amandavisconti Work w/Laura on #1104 (making sure all old events, e.g. 2023-2024 especially but maybe Jan 2018-July 2024 even?) are in events archive, then close that ticket

**Comment by jeremyboggs** [comment]
@amandavisconti Think once you update everyone about new process we can close this issue and work on #1150

**Comment by amandavisconti** [comment]
Yep! Yeehaw
