### ISSUE TITLE
Show "No upcoming events" if there are no upcoming events

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.github.io#986]
Currently, with no upcoming events, we simply display the "Upcoming Events" heading.

<img width="310" alt="Screenshot 2024-05-14 at 11 06 35 AM" src="https://github.com/scholarslab/scholarslab.org/assets/48310/9a0b8134-6f6f-4f70-89d0-268d07b5d385">

**Comment by amandavisconti** [comment]
Don't have to check every post; sort for most recent, compare against current date.

<p>Scholars' Lab's scheduled events for this term have all been completed. We sometimes have late additions to a term's events schedule; join [our newsletter](/newsletters) to make sure you hear about any short-notice speakers, workshops, and other events; as well as when our next term's event series is announced!</p>

**Comment by amandavisconti** [comment]
#1029 may change need for this

**Comment by amandavisconti** [comment]
closing as subsumed by LibCal events adding
